with open('./input/test.txt','r',encoding='utf-8') as file:
     s = file.readline()
     print(s)
     s = file.readline()
     print(s)
     s = file.readline()
     print(s)
     s = file.readline()
     print(s)
     s = file.readline()
     print(s)
     s = file.readline()
     print(s)
     print(file.readline())